import { getTokenMintWorker } from './mintWorkerClient.js';
import { getCredentialWorker } from './zkappWorkerClient.js';
console.log('COMPILING BUILD (TRYING FIRST AND NOT SLIM)', process.env.BUILD_HASH);
const CredentialWorker = getCredentialWorker();
const credentialWorker = new CredentialWorker();
await credentialWorker.compile();
console.log('THE LITTLE GUY(CredentialWorker) COMPILED', process.env.BUILD_HASH);
credentialWorker.terminate();
console.log('TERMINATED CredentialWorker... to stop o1js hitting the wasm 6.2GB limit and crashing, seriously try it without terminate. Tough but fair.');
const TokenMintWorker = getTokenMintWorker();
const tokenMintWorker = new TokenMintWorker();
await tokenMintWorker.compileAll();
console.log('THE LITTLE GUY(tokenMintWorker) COMPILED', process.env.BUILD_HASH);