import { Bytes, UInt64, UInt8 } from 'o1js';
import {
    provableRequestLeafHash,
    VerifiedRequest,
} from './ContractDepositAttestor.js';
import { EthInput, ethInputToBytes } from './ethVerifier.js';
import { Bytes20, Bytes32 } from './types.js';
import { decodeConsensusMptProof } from './utils.js';
import {
    proofOutputsVectors,
    requestLeafVectors,
    type ProofOutputsVector,
    type RequestLeafVector,
} from './test-vectors/proof-request-queue/index.js';

// These vectors are generated by the Rust side and vendored here. They pin the
// two encodings the SP1 guest and this circuit must agree on byte-for-byte: a
// divergence produces proofs that verify on one side and not the other.

const stripHexPrefix = (hex: string) => hex.slice(2);

function verifiedRequestFromVector(vector: RequestLeafVector) {
    return new VerifiedRequest({
        target: Bytes20.fromHex(stripHexPrefix(vector.target)),
        collectionKeysCount: UInt8.from(vector.collectionKeysCount),
        collectionKeys: vector.collectionKeys.map((key) =>
            Bytes32.fromHex(stripHexPrefix(key))
        ),
        value: Bytes32.fromHex(stripHexPrefix(vector.value)),
    });
}

function ethInputFromVector(vector: ProofOutputsVector) {
    return new EthInput({
        inputSlot: UInt64.from(vector.inputSlot),
        inputStoreHash: Bytes32.fromHex(stripHexPrefix(vector.inputStoreHash)),
        outputSlot: UInt64.from(vector.outputSlot),
        outputStoreHash: Bytes32.fromHex(
            stripHexPrefix(vector.outputStoreHash)
        ),
        executionStateRoot: Bytes32.fromHex(
            stripHexPrefix(vector.executionStateRoot)
        ),
        verifiedContractDepositsRoot: Bytes32.fromHex(
            stripHexPrefix(vector.verifiedContractDepositsRoot)
        ),
        nextSyncCommitteeHash: Bytes32.fromHex(
            stripHexPrefix(vector.nextSyncCommitteeHash)
        ),
        proofRequestQueueAddress: Bytes20.fromHex(
            stripHexPrefix(vector.proofRequestQueueAddress)
        ),
        inputQueueCursor: UInt64.from(vector.inputQueueCursor),
        outputQueueCursor: UInt64.from(vector.outputQueueCursor),
        outputBlockNumber: UInt64.from(vector.outputBlockNumber),
    });
}

describe('Proof request queue cross-language vectors', () => {
    describe('request leaf hash', () => {
        test('vector set is populated', () => {
            expect(requestLeafVectors.length).toBeGreaterThanOrEqual(6);
        });

        test.each(requestLeafVectors.map((v) => [v.name, v] as const))(
            'matches the Rust leaf for %s',
            (_name, vector) => {
                const leaf = provableRequestLeafHash(
                    verifiedRequestFromVector(vector)
                );
                expect(leaf.toBigInt().toString()).toBe(vector.leaf);
            }
        );

        test('the count disambiguates a supplied zero key from an absent one', () => {
            const oneKey = requestLeafVectors.find(
                (v) => v.name === 'one_key'
            )!;
            const twoKeys = requestLeafVectors.find(
                (v) => v.name === 'two_keys_second_zero'
            )!;

            // Same target, keys and value; only collectionKeysCount differs.
            expect(twoKeys.target).toBe(oneKey.target);
            expect(twoKeys.collectionKeys).toEqual(oneKey.collectionKeys);
            expect(twoKeys.value).toBe(oneKey.value);
            expect(twoKeys.collectionKeysCount).not.toBe(
                oneKey.collectionKeysCount
            );

            expect(
                provableRequestLeafHash(
                    verifiedRequestFromVector(oneKey)
                ).toBigInt()
            ).not.toBe(
                provableRequestLeafHash(
                    verifiedRequestFromVector(twoKeys)
                ).toBigInt()
            );
        });

        test('the target namespaces the leaf', () => {
            const vector = requestLeafVectors.find(
                (v) => v.name === 'one_key'
            )!;
            const request = verifiedRequestFromVector(vector);
            const foreign = new VerifiedRequest({
                ...request,
                target: Bytes20.fromHex('00'.repeat(19) + 'ff'),
            });

            expect(provableRequestLeafHash(request).toBigInt()).not.toBe(
                provableRequestLeafHash(foreign).toBigInt()
            );
        });
    });

    describe('ProofOutputs byte encoding', () => {
        test('vector set is populated', () => {
            expect(proofOutputsVectors.length).toBeGreaterThanOrEqual(3);
        });

        test.each(proofOutputsVectors.map((v) => [v.name, v] as const))(
            'assembles the Rust bytes for %s',
            (_name, vector) => {
                const bytes = ethInputToBytes(ethInputFromVector(vector));
                expect(bytes.length).toBe(220);
                expect(`0x${Bytes.from(bytes).toHex()}`).toBe(vector.bytes);
            }
        );

        test.each(proofOutputsVectors.map((v) => [v.name, v] as const))(
            'decodes the Rust bytes for %s',
            (_name, vector) => {
                const decoded = decodeConsensusMptProof({
                    public_values: {
                        buffer: {
                            data: Array.from(
                                Buffer.from(stripHexPrefix(vector.bytes), 'hex')
                            ),
                        },
                    },
                } as Parameters<typeof decodeConsensusMptProof>[0]);

                expect(decoded.inputSlot.toString()).toBe(vector.inputSlot);
                expect(decoded.outputSlot.toString()).toBe(vector.outputSlot);
                expect(decoded.inputQueueCursor.toString()).toBe(
                    vector.inputQueueCursor
                );
                expect(decoded.outputQueueCursor.toString()).toBe(
                    vector.outputQueueCursor
                );
                expect(decoded.outputBlockNumber.toString()).toBe(
                    vector.outputBlockNumber
                );
                expect(`0x${decoded.proofRequestQueueAddress.toHex()}`).toBe(
                    vector.proofRequestQueueAddress
                );
            }
        );

        test('decode rejects the previous 244-byte layout', () => {
            const vector = proofOutputsVectors[0];
            const padded = Buffer.concat([
                Buffer.from(stripHexPrefix(vector.bytes), 'hex'),
                Buffer.alloc(24),
            ]);

            expect(() =>
                decodeConsensusMptProof({
                    public_values: { buffer: { data: Array.from(padded) } },
                } as Parameters<typeof decodeConsensusMptProof>[0])
            ).toThrow(/220/);
        });

        test('round-trips decode back to the same bytes', () => {
            for (const vector of proofOutputsVectors) {
                const decoded = decodeConsensusMptProof({
                    public_values: {
                        buffer: {
                            data: Array.from(
                                Buffer.from(stripHexPrefix(vector.bytes), 'hex')
                            ),
                        },
                    },
                } as Parameters<typeof decodeConsensusMptProof>[0]);

                const reassembled = ethInputToBytes(new EthInput(decoded));
                expect(`0x${Bytes.from(reassembled).toHex()}`).toBe(
                    vector.bytes
                );
            }
        });
    });
});
