/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'MinaAccountValidationExample', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MinaAccountValidationExample__factory>
getContractFactory(name: 'MinaStateSettlementExample', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MinaStateSettlementExample__factory>
getContractFactory(name: 'NoriTokenBridge', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NoriTokenBridge__factory>

  getContractAt(name: 'MinaAccountValidationExample', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MinaAccountValidationExample>
getContractAt(name: 'MinaStateSettlementExample', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MinaStateSettlementExample>
getContractAt(name: 'NoriTokenBridge', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NoriTokenBridge>

  deployContract(name: 'MinaAccountValidationExample', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MinaAccountValidationExample>
deployContract(name: 'MinaStateSettlementExample', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MinaStateSettlementExample>
deployContract(name: 'NoriTokenBridge', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoriTokenBridge>

  deployContract(name: 'MinaAccountValidationExample', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MinaAccountValidationExample>
deployContract(name: 'MinaStateSettlementExample', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MinaStateSettlementExample>
deployContract(name: 'NoriTokenBridge', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoriTokenBridge>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  