/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace MinaAccountValidationExample {
      
    export type AlignedArgsStruct = {proofCommitment: BytesLike, provingSystemAuxDataCommitment: BytesLike, proofGeneratorAddr: BytesLike, batchMerkleRoot: BytesLike, merkleProof: BytesLike, verificationDataBatchIndex: BigNumberish, pubInput: BytesLike, batcherPaymentService: AddressLike}

    export type AlignedArgsStructOutput = [proofCommitment: string, provingSystemAuxDataCommitment: string, proofGeneratorAddr: string, batchMerkleRoot: string, merkleProof: string, verificationDataBatchIndex: bigint, pubInput: string, batcherPaymentService: string] & {proofCommitment: string, provingSystemAuxDataCommitment: string, proofGeneratorAddr: string, batchMerkleRoot: string, merkleProof: string, verificationDataBatchIndex: bigint, pubInput: string, batcherPaymentService: string }
  

    export type CompressedECPointStruct = {x: BytesLike, isOdd: boolean}

    export type CompressedECPointStructOutput = [x: string, isOdd: boolean] & {x: string, isOdd: boolean }
  

    export type TimingStruct = {initialMinimumBalance: BigNumberish, cliffTime: BigNumberish, cliffAmount: BigNumberish, vestingPeriod: BigNumberish, vestingIncrement: BigNumberish}

    export type TimingStructOutput = [initialMinimumBalance: bigint, cliffTime: bigint, cliffAmount: bigint, vestingPeriod: bigint, vestingIncrement: bigint] & {initialMinimumBalance: bigint, cliffTime: bigint, cliffAmount: bigint, vestingPeriod: bigint, vestingIncrement: bigint }
  

    export type PermissionsStruct = {editState: BigNumberish, access: BigNumberish, send: BigNumberish, rreceive: BigNumberish, setDelegate: BigNumberish, setPermissions: BigNumberish, setVerificationKeyAuth: BigNumberish, setVerificationKeyUint: BigNumberish, setZkappUri: BigNumberish, editActionState: BigNumberish, setTokenSymbol: BigNumberish, incrementNonce: BigNumberish, setVotingFor: BigNumberish, setTiming: BigNumberish}

    export type PermissionsStructOutput = [editState: bigint, access: bigint, send: bigint, rreceive: bigint, setDelegate: bigint, setPermissions: bigint, setVerificationKeyAuth: bigint, setVerificationKeyUint: bigint, setZkappUri: bigint, editActionState: bigint, setTokenSymbol: bigint, incrementNonce: bigint, setVotingFor: bigint, setTiming: bigint] & {editState: bigint, access: bigint, send: bigint, rreceive: bigint, setDelegate: bigint, setPermissions: bigint, setVerificationKeyAuth: bigint, setVerificationKeyUint: bigint, setZkappUri: bigint, editActionState: bigint, setTokenSymbol: bigint, incrementNonce: bigint, setVotingFor: bigint, setTiming: bigint }
  

    export type CommitmentStruct = {x: BytesLike, y: BytesLike}

    export type CommitmentStructOutput = [x: string, y: string] & {x: string, y: string }
  

    export type WrapIndexStruct = {sigmaComm: MinaAccountValidationExample.CommitmentStruct[], coefficientsComm: MinaAccountValidationExample.CommitmentStruct[], genericComm: MinaAccountValidationExample.CommitmentStruct, psmComm: MinaAccountValidationExample.CommitmentStruct, completeAddComm: MinaAccountValidationExample.CommitmentStruct, mulComm: MinaAccountValidationExample.CommitmentStruct, emulComm: MinaAccountValidationExample.CommitmentStruct, endomulScalarComm: MinaAccountValidationExample.CommitmentStruct}

    export type WrapIndexStructOutput = [sigmaComm: MinaAccountValidationExample.CommitmentStructOutput[], coefficientsComm: MinaAccountValidationExample.CommitmentStructOutput[], genericComm: MinaAccountValidationExample.CommitmentStructOutput, psmComm: MinaAccountValidationExample.CommitmentStructOutput, completeAddComm: MinaAccountValidationExample.CommitmentStructOutput, mulComm: MinaAccountValidationExample.CommitmentStructOutput, emulComm: MinaAccountValidationExample.CommitmentStructOutput, endomulScalarComm: MinaAccountValidationExample.CommitmentStructOutput] & {sigmaComm: MinaAccountValidationExample.CommitmentStructOutput[], coefficientsComm: MinaAccountValidationExample.CommitmentStructOutput[], genericComm: MinaAccountValidationExample.CommitmentStructOutput, psmComm: MinaAccountValidationExample.CommitmentStructOutput, completeAddComm: MinaAccountValidationExample.CommitmentStructOutput, mulComm: MinaAccountValidationExample.CommitmentStructOutput, emulComm: MinaAccountValidationExample.CommitmentStructOutput, endomulScalarComm: MinaAccountValidationExample.CommitmentStructOutput }
  

    export type VerificationKeyStruct = {maxProofsVerified: BigNumberish, actualWrapDomainSize: BigNumberish, wrapIndex: MinaAccountValidationExample.WrapIndexStruct}

    export type VerificationKeyStructOutput = [maxProofsVerified: bigint, actualWrapDomainSize: bigint, wrapIndex: MinaAccountValidationExample.WrapIndexStructOutput] & {maxProofsVerified: bigint, actualWrapDomainSize: bigint, wrapIndex: MinaAccountValidationExample.WrapIndexStructOutput }
  

    export type ZkappAccountStruct = {appState: BytesLike[], verificationKey: MinaAccountValidationExample.VerificationKeyStruct, zkappVersion: BigNumberish, actionState: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike], lastActionSlot: BigNumberish, provedState: boolean, zkappUri: BytesLike}

    export type ZkappAccountStructOutput = [appState: string[], verificationKey: MinaAccountValidationExample.VerificationKeyStructOutput, zkappVersion: bigint, actionState: [string, string, string, string, string], lastActionSlot: bigint, provedState: boolean, zkappUri: string] & {appState: string[], verificationKey: MinaAccountValidationExample.VerificationKeyStructOutput, zkappVersion: bigint, actionState: [string, string, string, string, string], lastActionSlot: bigint, provedState: boolean, zkappUri: string }
  

    export type AccountStruct = {publicKey: MinaAccountValidationExample.CompressedECPointStruct, tokenIdKeyHash: BytesLike, tokenSymbol: string, balance: BigNumberish, nonce: BigNumberish, receiptChainHash: BytesLike, delegate: MinaAccountValidationExample.CompressedECPointStruct, votingFor: BytesLike, timing: MinaAccountValidationExample.TimingStruct, permissions: MinaAccountValidationExample.PermissionsStruct, zkapp: MinaAccountValidationExample.ZkappAccountStruct}

    export type AccountStructOutput = [publicKey: MinaAccountValidationExample.CompressedECPointStructOutput, tokenIdKeyHash: string, tokenSymbol: string, balance: bigint, nonce: bigint, receiptChainHash: string, delegate: MinaAccountValidationExample.CompressedECPointStructOutput, votingFor: string, timing: MinaAccountValidationExample.TimingStructOutput, permissions: MinaAccountValidationExample.PermissionsStructOutput, zkapp: MinaAccountValidationExample.ZkappAccountStructOutput] & {publicKey: MinaAccountValidationExample.CompressedECPointStructOutput, tokenIdKeyHash: string, tokenSymbol: string, balance: bigint, nonce: bigint, receiptChainHash: string, delegate: MinaAccountValidationExample.CompressedECPointStructOutput, votingFor: string, timing: MinaAccountValidationExample.TimingStructOutput, permissions: MinaAccountValidationExample.PermissionsStructOutput, zkapp: MinaAccountValidationExample.ZkappAccountStructOutput }
  
    }

  export interface MinaAccountValidationExampleInterface extends Interface {
    getFunction(nameOrSignature: "validateAccount" | "validateAccountAndReturn"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'validateAccount', values: [MinaAccountValidationExample.AlignedArgsStruct]): string;
encodeFunctionData(functionFragment: 'validateAccountAndReturn', values: [MinaAccountValidationExample.AlignedArgsStruct]): string;

    decodeFunctionResult(functionFragment: 'validateAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateAccountAndReturn', data: BytesLike): Result;
  }

  

  export interface MinaAccountValidationExample extends BaseContract {
    
    connect(runner?: ContractRunner | null): MinaAccountValidationExample;
    waitForDeployment(): Promise<this>;

    interface: MinaAccountValidationExampleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    validateAccount: TypedContractMethod<
      [args: MinaAccountValidationExample.AlignedArgsStruct, ],
      [boolean],
      'view'
    >
    

    
    validateAccountAndReturn: TypedContractMethod<
      [args: MinaAccountValidationExample.AlignedArgsStruct, ],
      [MinaAccountValidationExample.AccountStructOutput],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'validateAccount'): TypedContractMethod<
      [args: MinaAccountValidationExample.AlignedArgsStruct, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'validateAccountAndReturn'): TypedContractMethod<
      [args: MinaAccountValidationExample.AlignedArgsStruct, ],
      [MinaAccountValidationExample.AccountStructOutput],
      'view'
    >;

    

    filters: {
      
    };
  }