/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MinaStateSettlementInterface extends Interface {
    getFunction(nameOrSignature: "BRIDGE_TRANSITION_FRONTIER_LEN" | "aligned" | "devnetFlag" | "isLedgerVerified" | "updateChain" | "verifiedLedgerHashes"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "LedgerHashVerified"): EventFragment;

    encodeFunctionData(functionFragment: 'BRIDGE_TRANSITION_FRONTIER_LEN', values?: undefined): string;
encodeFunctionData(functionFragment: 'aligned', values?: undefined): string;
encodeFunctionData(functionFragment: 'devnetFlag', values?: undefined): string;
encodeFunctionData(functionFragment: 'isLedgerVerified', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'updateChain', values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike, BigNumberish, BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'verifiedLedgerHashes', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'BRIDGE_TRANSITION_FRONTIER_LEN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'aligned', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'devnetFlag', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isLedgerVerified', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateChain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifiedLedgerHashes', data: BytesLike): Result;
  }

  
    export namespace LedgerHashVerifiedEvent {
      export type InputTuple = [ledgerHash: BytesLike];
      export type OutputTuple = [ledgerHash: string];
      export interface OutputObject {ledgerHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MinaStateSettlement extends BaseContract {
    
    connect(runner?: ContractRunner | null): MinaStateSettlement;
    waitForDeployment(): Promise<this>;

    interface: MinaStateSettlementInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BRIDGE_TRANSITION_FRONTIER_LEN: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    aligned: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    devnetFlag: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    isLedgerVerified: TypedContractMethod<
      [ledgerHash: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    updateChain: TypedContractMethod<
      [proofCommitment: BytesLike, provingSystemAuxDataCommitment: BytesLike, proofGeneratorAddr: BytesLike, batchMerkleRoot: BytesLike, merkleProof: BytesLike, verificationDataBatchIndex: BigNumberish, pubInput: BytesLike, batcherPaymentService: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifiedLedgerHashes: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BRIDGE_TRANSITION_FRONTIER_LEN'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'aligned'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'devnetFlag'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isLedgerVerified'): TypedContractMethod<
      [ledgerHash: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'updateChain'): TypedContractMethod<
      [proofCommitment: BytesLike, provingSystemAuxDataCommitment: BytesLike, proofGeneratorAddr: BytesLike, batchMerkleRoot: BytesLike, merkleProof: BytesLike, verificationDataBatchIndex: BigNumberish, pubInput: BytesLike, batcherPaymentService: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifiedLedgerHashes'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'LedgerHashVerified'): TypedContractEvent<LedgerHashVerifiedEvent.InputTuple, LedgerHashVerifiedEvent.OutputTuple, LedgerHashVerifiedEvent.OutputObject>;

    filters: {
      
      'LedgerHashVerified(bytes32)': TypedContractEvent<LedgerHashVerifiedEvent.InputTuple, LedgerHashVerifiedEvent.OutputTuple, LedgerHashVerifiedEvent.OutputObject>;
      LedgerHashVerified: TypedContractEvent<LedgerHashVerifiedEvent.InputTuple, LedgerHashVerifiedEvent.OutputTuple, LedgerHashVerifiedEvent.OutputObject>;
    
    };
  }