/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MinaStateSettlementExampleInterface extends Interface {
    getFunction(nameOrSignature: "BRIDGE_TRANSITION_FRONTIER_LEN" | "getChainLedgerHashes" | "getChainStateHashes" | "getTipLedgerHash" | "getTipStateHash" | "isLedgerVerified" | "updateChain"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'BRIDGE_TRANSITION_FRONTIER_LEN', values?: undefined): string;
encodeFunctionData(functionFragment: 'getChainLedgerHashes', values?: undefined): string;
encodeFunctionData(functionFragment: 'getChainStateHashes', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTipLedgerHash', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTipStateHash', values?: undefined): string;
encodeFunctionData(functionFragment: 'isLedgerVerified', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'updateChain', values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike, BigNumberish, BytesLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'BRIDGE_TRANSITION_FRONTIER_LEN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getChainLedgerHashes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getChainStateHashes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTipLedgerHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTipStateHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isLedgerVerified', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateChain', data: BytesLike): Result;
  }

  

  export interface MinaStateSettlementExample extends BaseContract {
    
    connect(runner?: ContractRunner | null): MinaStateSettlementExample;
    waitForDeployment(): Promise<this>;

    interface: MinaStateSettlementExampleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BRIDGE_TRANSITION_FRONTIER_LEN: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getChainLedgerHashes: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getChainStateHashes: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getTipLedgerHash: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getTipStateHash: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isLedgerVerified: TypedContractMethod<
      [ledgerHash: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    updateChain: TypedContractMethod<
      [proofCommitment: BytesLike, provingSystemAuxDataCommitment: BytesLike, proofGeneratorAddr: BytesLike, batchMerkleRoot: BytesLike, merkleProof: BytesLike, verificationDataBatchIndex: BigNumberish, pubInput: BytesLike, batcherPaymentService: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BRIDGE_TRANSITION_FRONTIER_LEN'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getChainLedgerHashes'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getChainStateHashes'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTipLedgerHash'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getTipStateHash'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isLedgerVerified'): TypedContractMethod<
      [ledgerHash: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'updateChain'): TypedContractMethod<
      [proofCommitment: BytesLike, provingSystemAuxDataCommitment: BytesLike, proofGeneratorAddr: BytesLike, batchMerkleRoot: BytesLike, merkleProof: BytesLike, verificationDataBatchIndex: BigNumberish, pubInput: BytesLike, batcherPaymentService: AddressLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }