/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface NoriTokenBridgeInterface extends Interface {
    getFunction(nameOrSignature: "DECIMALS" | "MAX_MAGNITUDE" | "WEI_PER_BRIDGE_UNIT" | "bridgeOperator" | "burnSoFarSet" | "codeChallengeToEthAddress" | "isConfigured" | "lockTokens" | "lockedTokens" | "setAlignedContracts" | "totalLocked" | "unlockTokens" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AccountValidationSet" | "StateSettlementSet" | "TokensLocked" | "TokensUnlocked"): EventFragment;

    encodeFunctionData(functionFragment: 'DECIMALS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_MAGNITUDE', values?: undefined): string;
encodeFunctionData(functionFragment: 'WEI_PER_BRIDGE_UNIT', values?: undefined): string;
encodeFunctionData(functionFragment: 'bridgeOperator', values?: undefined): string;
encodeFunctionData(functionFragment: 'burnSoFarSet', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'codeChallengeToEthAddress', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isConfigured', values?: undefined): string;
encodeFunctionData(functionFragment: 'lockTokens', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lockedTokens', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setAlignedContracts', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'totalLocked', values?: undefined): string;
encodeFunctionData(functionFragment: 'unlockTokens', values: [BigNumberish, BytesLike, BytesLike, BytesLike, BytesLike, BytesLike, BigNumberish, BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DECIMALS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_MAGNITUDE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WEI_PER_BRIDGE_UNIT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bridgeOperator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burnSoFarSet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'codeChallengeToEthAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isConfigured', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockedTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAlignedContracts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalLocked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unlockTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace AccountValidationSetEvent {
      export type InputTuple = [newAddress: AddressLike];
      export type OutputTuple = [newAddress: string];
      export interface OutputObject {newAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StateSettlementSetEvent {
      export type InputTuple = [newAddress: AddressLike];
      export type OutputTuple = [newAddress: string];
      export interface OutputObject {newAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensLockedEvent {
      export type InputTuple = [user: AddressLike, attestationHash: BigNumberish, amount: BigNumberish, when: BigNumberish];
      export type OutputTuple = [user: string, attestationHash: bigint, amount: bigint, when: bigint];
      export interface OutputObject {user: string, attestationHash: bigint, amount: bigint, when: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensUnlockedEvent {
      export type InputTuple = [pubKeyTokenIdHash: BigNumberish, amount: BigNumberish, receiver: AddressLike, when: BigNumberish];
      export type OutputTuple = [pubKeyTokenIdHash: bigint, amount: bigint, receiver: string, when: bigint];
      export interface OutputObject {pubKeyTokenIdHash: bigint, amount: bigint, receiver: string, when: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NoriTokenBridge extends BaseContract {
    
    connect(runner?: ContractRunner | null): NoriTokenBridge;
    waitForDeployment(): Promise<this>;

    interface: NoriTokenBridgeInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DECIMALS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_MAGNITUDE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    WEI_PER_BRIDGE_UNIT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    bridgeOperator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    burnSoFarSet: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    codeChallengeToEthAddress: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    isConfigured: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    lockTokens: TypedContractMethod<
      [attestationHash: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    lockedTokens: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    setAlignedContracts: TypedContractMethod<
      [_stateSettlementAddr: AddressLike, _accountValidationAddr: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalLocked: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unlockTokens: TypedContractMethod<
      [toUnlockAmount: BigNumberish, proofCommitment: BytesLike, provingSystemAuxDataCommitment: BytesLike, proofGeneratorAddr: BytesLike, batchMerkleRoot: BytesLike, merkleProof: BytesLike, verificationDataBatchIndex: BigNumberish, pubInput: BytesLike, batcherPaymentService: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DECIMALS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_MAGNITUDE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'WEI_PER_BRIDGE_UNIT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bridgeOperator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'burnSoFarSet'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'codeChallengeToEthAddress'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isConfigured'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lockTokens'): TypedContractMethod<
      [attestationHash: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'lockedTokens'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setAlignedContracts'): TypedContractMethod<
      [_stateSettlementAddr: AddressLike, _accountValidationAddr: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalLocked'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unlockTokens'): TypedContractMethod<
      [toUnlockAmount: BigNumberish, proofCommitment: BytesLike, provingSystemAuxDataCommitment: BytesLike, proofGeneratorAddr: BytesLike, batchMerkleRoot: BytesLike, merkleProof: BytesLike, verificationDataBatchIndex: BigNumberish, pubInput: BytesLike, batcherPaymentService: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AccountValidationSet'): TypedContractEvent<AccountValidationSetEvent.InputTuple, AccountValidationSetEvent.OutputTuple, AccountValidationSetEvent.OutputObject>;
getEvent(key: 'StateSettlementSet'): TypedContractEvent<StateSettlementSetEvent.InputTuple, StateSettlementSetEvent.OutputTuple, StateSettlementSetEvent.OutputObject>;
getEvent(key: 'TokensLocked'): TypedContractEvent<TokensLockedEvent.InputTuple, TokensLockedEvent.OutputTuple, TokensLockedEvent.OutputObject>;
getEvent(key: 'TokensUnlocked'): TypedContractEvent<TokensUnlockedEvent.InputTuple, TokensUnlockedEvent.OutputTuple, TokensUnlockedEvent.OutputObject>;

    filters: {
      
      'AccountValidationSet(address)': TypedContractEvent<AccountValidationSetEvent.InputTuple, AccountValidationSetEvent.OutputTuple, AccountValidationSetEvent.OutputObject>;
      AccountValidationSet: TypedContractEvent<AccountValidationSetEvent.InputTuple, AccountValidationSetEvent.OutputTuple, AccountValidationSetEvent.OutputObject>;
    

      'StateSettlementSet(address)': TypedContractEvent<StateSettlementSetEvent.InputTuple, StateSettlementSetEvent.OutputTuple, StateSettlementSetEvent.OutputObject>;
      StateSettlementSet: TypedContractEvent<StateSettlementSetEvent.InputTuple, StateSettlementSetEvent.OutputTuple, StateSettlementSetEvent.OutputObject>;
    

      'TokensLocked(address,uint256,uint256,uint256)': TypedContractEvent<TokensLockedEvent.InputTuple, TokensLockedEvent.OutputTuple, TokensLockedEvent.OutputObject>;
      TokensLocked: TypedContractEvent<TokensLockedEvent.InputTuple, TokensLockedEvent.OutputTuple, TokensLockedEvent.OutputObject>;
    

      'TokensUnlocked(uint256,uint256,address,uint256)': TypedContractEvent<TokensUnlockedEvent.InputTuple, TokensUnlockedEvent.OutputTuple, TokensUnlockedEvent.OutputObject>;
      TokensUnlocked: TypedContractEvent<TokensUnlockedEvent.InputTuple, TokensUnlockedEvent.OutputTuple, TokensUnlockedEvent.OutputObject>;
    
    };
  }