import { getTokenMintWorker } from './mintWorkerClient.js';
import { getCredentialWorker } from './zkappWorkerClient.js';
console.log('COMPILING BUILD SLIM', process.env.BUILD_HASH);
const CredentialWorker = getCredentialWorker();
const credentialWorker = new CredentialWorker();
await credentialWorker.compile();
console.log('THE LITTLE GUY(CredentialWorker) COMPILED', process.env.BUILD_HASH);
credentialWorker.signalTerminate();
console.log('TERMINATED (via signal) CredentialWorker... to stop o1js hitting the wasm 6.2GB limit and crashing, seriously try it without terminate. Tough but fair.');
//console.log('Called terminate on the little guy (credentialWorker). Giving the runtime a bit of time to clean up.');
//await new Promise((res) => setTimeout(res,10000));
console.log('Compiling tokenMintWorker');
const TokenMintWorker = getTokenMintWorker();
const tokenMintWorker = new TokenMintWorker();
await tokenMintWorker.compileAll();
console.log('THE LITTLE GUY(tokenMintWorker) COMPILED', process.env.BUILD_HASH);
//tokenMintWorker.signalTerminate();